name: Respond to Pull Request

on:
  pull_request:
    types: [opened, synchronize]
  pull_request_review_comment:
    types: [ created ]
  issues:
    types: opened
  issue_comment:
    types:
      - created

jobs:
  respond:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print pull request number
      run: |  
        echo "Pull Request Number - ${{ github.event.pull_request.number }}"
        echo "Organization - ${{ github.repository_owner }}"
        echo "Repository Name - ${{ github.repository }}"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate diff
      run: |
        git fetch origin ${{ github.base_ref }}
        git diff origin/${{ github.base_ref }} HEAD > temp.txt

    #- name: Upload diff as artifact
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: diff-file
    #    path: temp.txt

    - name: Run Python
      env:
        ANTHROPIC_API_KEY: "${{ secrets.ANTHROPIC_API_KEY }}"
        GITHUB_API_KEY: "${{ secrets.GITHUB_TOKEN }}"
      run: |
        python actions/manager.py response-pull-request ${{ github.repository }} ${{ github.event.pull_request.number }} ${{ github.event.issue.number }}

    - name: Remove temp files
      run: |
        rm temp.txt
