name: Respond to Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  respond:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print pull request number
      run: echo "Pull Request Number - ${{ github.event.pull_request.number }}"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
   
    - name: Run action
      env:
        ANTHROPIC_API_KEY: "${{ secrets.ANTHROPIC_API_KEY }}"
      run: |
        python actions/manager.py response-pull-request ${{ github.event.pull_request.number }}
